exports.up = function (knex) {
  return knex.schema.createTable("transferencias", function (table) {
    table.increments();
    table.string("dataAtual").notNullable();
    table.string("numeroControle").notNullable();
    table.string("unidadeDestino").notNullable();
    table.string("nomeUnidadeDestino").notNullable();
    table.string("enderecoUnidadeDestino").notNullable();
    table.string("transportador").notNullable();
    table.string("conferente").notNullable();
    table.string("placaVeiculo").notNullable();
    //
    table.string("filialOrigem_1").notNullable();
    table.string("notaFiscal_1").notNullable();
    table.string("tipoOperacao_1").notNullable();
    table.string("codigo_1").notNullable();
    table.string("descricaoProduto_1").notNullable();
    table.string("quantidadeProduto_1").notNullable();
    table.string("observacao_1").notNullable();
    //
    table.string("filialOrigem_2");
    table.string("notaFiscal_2");
    table.string("tipoOperacao_2");
    table.string("codigo_2");
    table.string("descricaoProduto_2");
    table.string("quantidadeProduto_2");
    table.string("observacao_2");
    //
    table.string("filialOrigem_3");
    table.string("notaFiscal_3");
    table.string("tipoOperacao_3");
    table.string("codigo_3");
    table.string("descricaoProduto_3");
    table.string("quantidadeProduto_3");
    table.string("observacao_3");
    //
    table.string("filialOrigem_4");
    table.string("notaFiscal_4");
    table.string("tipoOperacao_4");
    table.string("codigo_4");
    table.string("descricaoProduto_4");
    table.string("quantidadeProduto_4");
    table.string("observacao_4");
    //
    table.string("filialOrigem_5");
    table.string("notaFiscal_5");
    table.string("tipoOperacao_5");
    table.string("codigo_5");
    table.string("descricaoProduto_5");
    table.string("quantidadeProduto_5");
    table.string("observacao_5");
    //
    table.string("filialOrigem_6");
    table.string("notaFiscal_6");
    table.string("tipoOperacao_6");
    table.string("codigo_6");
    table.string("descricaoProduto_6");
    table.string("quantidadeProduto_6");
    table.string("observacao_6");
    //
    table.string("filialOrigem_7");
    table.string("notaFiscal_7");
    table.string("tipoOperacao_7");
    table.string("codigo_7");
    table.string("descricaoProduto_7");
    table.string("quantidadeProduto_7");
    table.string("observacao_7");
    //
    table.string("filialOrigem_8");
    table.string("notaFiscal_8");
    table.string("tipoOperacao_8");
    table.string("codigo_8");
    table.string("descricaoProduto_8");
    table.string("quantidadeProduto_8");
    table.string("observacao_8");
    //
    table.string("filialOrigem_9");
    table.string("notaFiscal_9");
    table.string("tipoOperacao_9");
    table.string("codigo_9");
    table.string("descricaoProduto_9");
    table.string("quantidadeProduto_9");
    table.string("observacao_9");
    //
    table.string("filialOrigem_10");
    table.string("notaFiscal_10");
    table.string("tipoOperacao_10");
    table.string("codigo_10");
    table.string("descricaoProduto_10");
    table.string("quantidadeProduto_10");
    table.string("observacao_10");
    //
    table.string("filialOrigem_11");
    table.string("notaFiscal_11");
    table.string("tipoOperacao_11");
    table.string("codigo_11");
    table.string("descricaoProduto_11");
    table.string("quantidadeProduto_11");
    table.string("observacao_11");
    //
    table.string("filialOrigem_12");
    table.string("notaFiscal_12");
    table.string("tipoOperacao_12");
    table.string("codigo_12");
    table.string("descricaoProduto_12");
    table.string("quantidadeProduto_12");
    table.string("observacao_12");
    //
    table.string("filialOrigem_13");
    table.string("notaFiscal_13");
    table.string("tipoOperacao_13");
    table.string("codigo_13");
    table.string("descricaoProduto_13");
    table.string("quantidadeProduto_13");
    table.string("observacao_13");
    //
    table.string("filialOrigem_14");
    table.string("notaFiscal_14");
    table.string("tipoOperacao_14");
    table.string("codigo_14");
    table.string("descricaoProduto_14");
    table.string("quantidadeProduto_14");
    table.string("observacao_14");
    //
    table.string("filialOrigem_15");
    table.string("notaFiscal_15");
    table.string("tipoOperacao_15");
    table.string("codigo_15");
    table.string("descricaoProduto_15");
    table.string("quantidadeProduto_15");
    table.string("observacao_15");
    //
    table.string("filialOrigem_16");
    table.string("notaFiscal_16");
    table.string("tipoOperacao_16");
    table.string("codigo_16");
    table.string("descricaoProduto_16");
    table.string("quantidadeProduto_16");
    table.string("observacao_16");
    //
    table.string("filialOrigem_17");
    table.string("notaFiscal_17");
    table.string("tipoOperacao_17");
    table.string("codigo_17");
    table.string("descricaoProduto_17");
    table.string("quantidadeProduto_17");
    table.string("observacao_17");
    //
    table.string("filialOrigem_18");
    table.string("notaFiscal_18");
    table.string("tipoOperacao_18");
    table.string("codigo_18");
    table.string("descricaoProduto_18");
    table.string("quantidadeProduto_18");
    table.string("observacao_18");
    //
    table.string("filialOrigem_19");
    table.string("notaFiscal_19");
    table.string("tipoOperacao_19");
    table.string("codigo_19");
    table.string("descricaoProduto_19");
    table.string("quantidadeProduto_19");
    table.string("observacao_19");
    //
    table.string("filialOrigem_20");
    table.string("notaFiscal_20");
    table.string("tipoOperacao_20");
    table.string("codigo_20");
    table.string("descricaoProduto_20");
    table.string("quantidadeProduto_20");
    table.string("observacao_20");
    //
    table.timestamp("created_at");
    table.timestamp("updated_at");
  });
};

exports.down = function (knex) {
  return knex.schema.dropTable("transferencias");
};
